// Newsletter configuration - Auto-generated by GitHub Actions
// This file is created/updated by the build-with-token.yml workflow
// The token is used to trigger repository_dispatch events
// The actual processing uses WORKHUB_GH_PAT secret server-side
window.NEWSLETTER_CONFIG = {
  githubToken: '',
  repo: 'x0bi3/Work-Hub',
  useRepositoryDispatch: true
};
