<<<<<<< HEAD
// Newsletter configuration - Auto-generated by GitHub Actions
// This file is created/updated by the build-with-token.yml workflow
// The token is used to trigger repository_dispatch events
// The actual processing uses WORKHUB_GH_PAT secret server-side
window.NEWSLETTER_CONFIG = {
  githubToken: '',
  repo: 'x0bi3/Work-Hub',
  useRepositoryDispatch: true
=======
// Newsletter configuration
// This file is generated by GitHub Actions
window.NEWSLETTER_CONFIG = {
  useRepositoryDispatch: true,
  repo: 'x0bi3/Work-Hub',
  // Token should be set via localStorage.setItem('github_token', 'YOUR_TOKEN')
  // Or use a public token with minimal permissions (repo scope, read-only)
>>>>>>> ae973968e7d36fd9c467f7cbb8953fdfb2329c65
};
