// Newsletter configuration
// This file is generated by GitHub Actions
window.NEWSLETTER_CONFIG = {
  useRepositoryDispatch: true,
  repo: 'x0bi3/Work-Hub',
  // Token should be set via localStorage.setItem('github_token', 'YOUR_TOKEN')
  // Or use a public token with minimal permissions (repo scope, read-only)
};
